### ISSUE TITLE
macOS compilation

### ISSUE THREAD

**Issue by grylem** [neostreet/command_line_tools#1]
Hi
is it possible to compile your tools on macOS?
Tried to compile first_line.c and some others but
use of undeclared identifier 'bVerbose' and some others errors.
Thanks.

**Comment by neostreet** [comment]
You need to use g++ as the compiler, not gcc, since these tools use the C++
bool type. Or whatever C++ compiler you have available.

**Comment by grylem** [comment]
Many thanks
